server:
  port: 8082

spring:
  application:
    name: users-service
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/crm_platform}
    username: ${DB_USERNAME:crm_user}
    password: ${DB_PASSWORD:crm_password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
        
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    ignore-migration-patterns: "*:missing"
    
  cache:
    type: ${CACHE_TYPE:caffeine}
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 1
      
eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: ${TRACING_ENABLED:false}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
      
logging:
  level:
    com.crm.platform.users: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    zipkin2.reporter: WARN  # Reduce Zipkin noise when not available
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/users-service.log