# Local development overrides
# This file is automatically loaded by docker-compose
# Place this in the root directory for easy local development

services:
  discovery-server:
    build:
      context: .
      dockerfile: services/discovery-server/Dockerfile.dev
    ports:
      - "8761:8761"
      - "5005:5005"
    volumes:
      - ./services/discovery-server/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile.dev
    ports:
      - "8081:8081"
      - "5006:5005"
    volumes:
      - ./services/auth-service/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=crm_user
      - SPRING_DATASOURCE_PASSWORD=crm_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PASSWORD=redis_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - postgres
      - redis
      - discovery-server

  tenant-service:
    build:
      context: .
      dockerfile: services/tenant-service/Dockerfile.dev
    ports:
      - "8082:8082"
      - "5007:5005"
    volumes:
      - ./services/tenant-service/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tenant_db
      - SPRING_DATASOURCE_USERNAME=crm_user
      - SPRING_DATASOURCE_PASSWORD=crm_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - postgres
      - discovery-server

  users-service:
    build:
      context: .
      dockerfile: services/users-service/Dockerfile.dev
    ports:
      - "8083:8083"
      - "5008:5005"
    volumes:
      - ./services/users-service/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users_db
      - SPRING_DATASOURCE_USERNAME=crm_user
      - SPRING_DATASOURCE_PASSWORD=crm_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - postgres
      - discovery-server

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crm_platform
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/docker/config/postgres/init:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis_password

volumes:
  postgres_data:

networks:
  default:
    name: crm-network