services:
  discovery-server:
    build:
      context: ../../  # Path to project root (adjust as needed)
      dockerfile: services/discovery-server/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
