name: Cleanup Old Docker Images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup Old Images
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [auth-service, tenant-service, users-service, discovery-server]
    
    steps:
    - name: Delete old images
      uses: actions/delete-package-versions@v4
      with:
        package-name: crm-${{ matrix.service }}
        package-type: container
        min-versions-to-keep: 10
        delete-only-untagged-versions: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}